config/routes.rb
Rails.application.routes.draw do
  
  resources :birthtrackers
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/birthtracker.rb
class Birthtracker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/birthtrackers_controller.rb
class BirthtrackersController < ApplicationController
  before_action :set_birthtracker, only: %i[ show edit update destroy ]

  # GET /birthtrackers or /birthtrackers.json
  def index
    @birthtrackers = Birthtracker.all
  end

  # GET /birthtrackers/1 or /birthtrackers/1.json
  def show
  end

  # GET /birthtrackers/new
  def new
    @birthtracker = Birthtracker.new
  end

  # GET /birthtrackers/1/edit
  def edit
  end

  # POST /birthtrackers or /birthtrackers.json
  def create
    @birthtracker = Birthtracker.new(birthtracker_params)

    respond_to do |format|
      if @birthtracker.save
        format.html { redirect_to @birthtracker, notice: "Birthtracker was successfully created." }
        format.json { render :show, status: :created, location: @birthtracker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @birthtracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birthtrackers/1 or /birthtrackers/1.json
  def update
    respond_to do |format|
      if @birthtracker.update(birthtracker_params)
        format.html { redirect_to @birthtracker, notice: "Birthtracker was successfully updated." }
        format.json { render :show, status: :ok, location: @birthtracker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @birthtracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birthtrackers/1 or /birthtrackers/1.json
  def destroy
    @birthtracker.destroy
    respond_to do |format|
      format.html { redirect_to birthtrackers_url, notice: "Birthtracker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def index
    @birthtrackers = Birthtracker.all
    @thisWeek = Date.today +7
    @date = Date.today
    @year = Date.today.strftime("%Y")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_birthtracker
      @birthtracker = Birthtracker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def birthtracker_params
      params.require(:birthtracker).permit(:first_name, :last_name, :email, :birthdate, :gift_received)
    end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthtrackers_helper.rb
module BirthtrackersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/birthtrackers/_form.html.erb
<%= form_with(model: birthtracker) do |form| %>
  <% if birthtracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(birthtracker.errors.count, "error") %> prohibited this birthtracker from being saved:</h2>

      <ul>
        <% birthtracker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :birthdate %>
    <%= form.date_field :birthdate,class:"form-control" %>
  </div>

 
  <div class="field form-group">
  <%= form.label :gift_received %>
  <%= form.text_field :gift_received,class:"form-control" %>
</div>

<br/>
  <div class="actions",>
    <%= form.submit class:"btn btn-info" %>
  </div>

  
<% end %>

app/views/birthtrackers/edit.html.erb
<h1>Editing Birthtracker</h1>

<%= render 'form', birthtracker: @birthtracker %>
<br/>
<%= link_to 'Show', @birthtracker,class:"btn btn-info" %> 
<%= link_to 'Back', birthtrackers_path,class:"btn btn-info" %>

app/views/birthtrackers/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Employees</h1>-->

<table class="table table table-bordered table table-hover">
  <thead class="table-dark">
    
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Birthdate</th>
      <th>Status</th>
      <th>Gift Received</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birthtrackers.each do |birthtracker| %>
      <tr>
        
        <td><%= birthtracker.first_name %></td>
        <td><%= birthtracker.last_name %></td>
        <td><%= birthtracker.email %></td>
        <td><%= birthtracker.birthdate.strftime("%m-%d-%Y") %></td>
        <%= birthtracker.status %>
        <% if birthtracker.birthdate.strftime("%m-%d%") > @thisWeek.strftime("%m-%d%") %>
        <td style="background-color:#FFFF00"><%= birthtracker.status %></td>
        <% elsif birthtracker.birthdate.strftime("%m-%d%") < @thisWeek.strftime("%m-%d%") %>
        <td style="background-color:#008000"><%= birthtracker.status %></td>
        <% else birthtracker.birthdate.strftime("%m-%d") == @date.strftime("%m-%d") %>
        <td style="background-color:#FF0000"><%= birthtracker.status %></td>
        <% end %>
        <% if birthtracker.birthdate.strftime("%m-%d") >= @thisWeek.strftime("%m-%d") %>
        <td>false</td>
        <%elsif birthtracker.birthdate.strftime("%m-%d") < @thisWeek.strftime("%m-%d") %>
        <td>true</td>
        <% end %>
        <%=birthtracker.gift_received %>
        <td><%= link_to 'Show', birthtracker %></td>
        <td><%= link_to 'Edit', edit_birthtracker_path(birthtracker) %></td>
        <td><%= link_to 'Destroy', birthtracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employees', new_birthtracker_path, class:"btn btn-info" %>

app/views/birthtrackers/new.html.erb
<h1>Add New Employee</h1>

<%= render 'form', birthtracker: @birthtracker %>
<br/>
<%= link_to 'Back', birthtrackers_path,class:"btn btn-info" %>

app/views/birthtrackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @birthtracker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @birthtracker.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @birthtracker.email %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @birthtracker.birthdate %>
</p>


<%= link_to 'Edit', edit_birthtracker_path(@birthtracker),class:"btn btn-info" %> 
<%= link_to 'Back', birthtrackers_path, class:"btn btn-info" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Mataverse',root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
          <%= link_to "About Us", home_about_path,class:"nav-link" %>
        </li>
       
       <li class="nav-item">
          <%= link_to "Employees", birthtrackers_path,class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Add Employees", new_birthtracker_path,class:"nav-link" %>
        </li>
  
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us </h1>

app/views/home/index.html.erb
<h1>Mataverse</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Birthday Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    

    <%=render 'home/header'%>
    <div class="container">
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>